---
title: "TITLE OF PAPER "
subtitle: "DELETE IF NOT USED"
author: "GROUP MEMBER NAMES HERE"
date: "`r Sys.Date()`"
output:    
      html_document:
         toc: yes
         toc_float: yes
---


```{r setup, include = FALSE}
#load packages, read in your dataset if external to a package, 
#and set global options. I have set all code chunks to not echo,
#and to not print messages or warnings.  If you want to echo a particular code chunk to highlight something, you can do this individually for that code chunk.


library(tidyverse)        #umbrella package
library(tidymodels)       #modeling
knitr::opts_chunk$set( echo = FALSE,    
                       message = FALSE,
                       warning = FALSE)

```

## Introduction

<!--- Delete the following text and write your introduction in its place  --->

This section was completed as part of the Introduction section of your proposal and may be mostly reused with some editing of course to ensure it flows with the material you are now going to be adding  by way of model building and results. 

In terms of additional statistical content required in this section , be sure that you include: 

 - a clear description of the response and explanatory variables your team will be considering
 - if you will be working with a transformation of the response variable, please describe this here with before and after pictures.
 - if you will be recoding any of the variables (for example, collapsing categories in a categorical variable with numerous levels), please describe this here.


## Section 2 - Model building


<!--- Delete the following text and write your individual model building in its place.Create code chunks as you need for your analysis. --->

In this section, your group will build several models for the response variable mentioned in the Introduction. Each group member is responsible for proposing and fitting one model each. In other words, groups of size 3 will build three models, while groups of size 2 or 4 will build two or four models respectively. Please see the project instructions for full details.


### Section 2.1 - Model proposed by XXX

Each group member must independently write a subsection with the title **Model proposed by XXX** with XXX filled in with your name, which clearly describes and justifies their model building process. You can share exploratory plots as well as plots of null distributions with shaded p-values, bootstrapped distributions, p-values, The subsection must also include model estimates and also the fitted model equation. 


Section 2 must conclude with a table which lists the models developed by each member of the group. If you have three group members, that's three models. The table must clearly display the training $R^2_{adj}$ for each model and also the testing **RMSE** for each model.


## Section 3 - Results 


<!--- Delete the following text and write your individual model building in its place.Create code chunks as you need for your analysis. --->


In this section you will present the results of the **best** model of the ones proposed in the previous section. 

- All group members must collaborate on writing and coding for this section.

- The narrative must begin with the choice of the best model and the reasoning behind this choice. Note: interpretability of the model, adjusted $R^2$ and size of the **RMSE** are all factors which should influence this decision. 

- Fit the best model to **the full data set** and carefully interpret all the coefficients in context. 

 - Focus on telling the story of how the variables relate to the response and answering the scientific questions raised by your group in the Introduction. 


## Bibliography

<!--- Delete this section if not used. You may use the MLA or ALP format for listing references.  --->