---
title: "Rate my Prof: Model validation"
subtitle: "STAT 311 Autumn 2024"
date: "`r Sys.Date()`"
output:    
      html_document:
         toc: yes
         toc_float: yes
---


We will return to the `evals` dataframe from the **openintro** package one last time to practice the workflow for training and testing models. 


Let's go ahead and load the packages we will need for the analysis.

## Packages

We will work with the **tidyverse**, **tidymodels** and the **openintro** packages as before. 



```{r setup, message = FALSE, warning = FALSE}
#load packages and set global options 

library(tidyverse)     #umbrella package 
library(openintro)     #for the data
library(tidymodels)    #for model fitting/model comparison   

```

Load the dataset `evals` into your working environment as well.

## Exercises 

### Exercise 1

Write code to randomly create two subsets called `evals_train` and `evals_test` by randomly choosing 80% of the rows in the `evals` dataframe for the training data and the remaining 20% for the testing. (Use 11 as the random number seed)


Over the last two weeks, we have considered the following three models for these data:

- `model1`: score ~ bty_avg + gender 

- `model2`: score ~ bty_avg*gender

- `model3`: score ~ bty_avg + cls_perc_eval + cls_level



### Exercise 2

Fit Model 1 using the `evals_train` data. Save the output from running `lm` in an object called `model1`. Also find the adjusted Rsquared for this model and enter it in the table below.


### Exercise 3

Use `model1` to predict outcomes for the testing data `evals_test`. 


### Exercise 4

Calculate the Root Mean Square Error of prediction for `model1` model using `evals_test`. Enter this number in the table below.


### Exercise 5

Repeat exercises 2 and 3 for `model2` and `model3`. Then fill in the blanks in the table below showing the adjusted R-squared and also the RMSE for each model.


**PARTICIPATION 6: Please record the training adjusted R-square and the testing RMSE for the models  2 and 3 in the table below. Then enter the answers in CANVAS. **

|Model | Training adjusted R2  (%)   | Testing RMSE
|----- | ----------------------------|-------------            
|1     |                             | 
|2     |                             |  
|3     |                             | 

 


## Acknowledgment

This activity is from Data Science in a Box